# Generated by Django 4.2.3 on 2023-07-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_urbain', models.DecimalField(decimal_places=2, max_digits=4)),
                ('extra_urbain', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mixte', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hateur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('empattement', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reservoir', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habitabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_place', models.IntegerField()),
                ('volume_coffre', models.IntegerField()),
                ('volume_coffre_utile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_moteur', models.CharField(max_length=100)),
                ('cylindre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('energie', models.CharField(max_length=100)),
                ('architecture', models.CharField(max_length=100)),
                ('alimentation', models.CharField(max_length=100)),
                ('injection', models.CharField(max_length=100)),
                ('alésage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('course', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dispostion', models.CharField(max_length=100)),
                ('soupape', models.IntegerField()),
                ('puissance_max', models.IntegerField()),
                ('regime_puissance_max', models.IntegerField()),
                ('couple_max', models.IntegerField()),
                ('regime_couple_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitesse_max', models.IntegerField()),
                ('depart_arreter', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drag', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pneu', models.CharField(max_length=100)),
                ('taille_roue_avant', models.CharField(max_length=100)),
                ('taille_roue_arriere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.CharField(max_length=100)),
                ('materiel_chassis', models.CharField(max_length=100)),
                ('diametre_braquage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type_suspension_avant', models.CharField(max_length=200)),
                ('type_suspension_arriere', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boite_de_vitesse', models.CharField(max_length=100)),
                ('rapport', models.IntegerField()),
                ('mode_transmission', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('prix_depart', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consommation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche_technique.consommation')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche_technique.dimension')),
                ('fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche_technique.fabricant')),
                ('habitabilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche_technique.habitabilite')),
                ('moteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche_technique.moteur')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche_technique.performance')),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche_technique.pneu')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche_technique.technique')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche_technique.transmission')),
            ],
        ),
    ]
