# Generated by Django 4.2.3 on 2023-07-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_technique', '0002_alter_moteur_cylindre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moteur',
            name='cylindre',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
